apiVersion: v1
kind: Service
metadata:
  name:  pintu-rtp-service
  namespace: pintu
spec:
  type: NodePort
  selector:
    app: pintu-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
